name: LotoxShop
version: '${version}'
main: fr.nicknqck.LotoxShop
api-version: '1.20'
authors: [NickNqck]
description: A simple minecraft market plugin for Lotox
commands:
  market:
    description: the access to the plugin market
  pay:
    description: To pay
  furnace:
    description: To cook what you want
  tpa:
    description: To tp